version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%H:%M:%S'
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s (%(module)s:%(funcName)s:%(lineno)d): %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/markdown_mcp.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  MarkdownSplitter:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  MarkdownMCPServer:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  __main__:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  mcp.server:
    level: WARNING
    handlers: [console]
    propagate: false
  
  mcp.server.lowlevel:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]